<?php
$helper = $this->helper('Conceptive\AdvanceSearch\Helper\Data');
$bg_color = $helper->getGeneralConfig('bg_color');
$hv_color = $helper->getGeneralConfig('hv_color');
$popupEnable = $helper->getGeneralConfig('popup');
$popupEnable = $block->getNameInLayout() == 'cc-search-form' ? false : $popupEnable;
$popupEnableClass = ($popupEnable) ? 'popup-modal' : '';
$attributes = $block->getDisplayAttributes();
$attributesColl = explode(',', $attributes);

?>
<style>
    .ccsearch-container .action.primary {
        background-color: <?php echo "#" . $bg_color; ?>;
        border: 1px solid <?php echo "#" . $bg_color; ?>;
    }

    .ccsearch-container .action.primary:hover {
        background-color: <?php echo "#" . $hv_color; ?>;
        border: 1px solid <?php echo "#" . $hv_color; ?>;
    }
</style>
<div class="ccsearch-container <?php /* @noEscape */ echo $popupEnableClass ?>" <?= ($popupEnable)? 'style="display:none"' : '' ?> >
    <form action="" method="POST" class="ccsearch-form">
        <div class="ajax-advanced-search">
            <h2 class="form-title"><?php echo __('Advance Product Search'); ?></h2>
            <div class="ajax-advanced-search-main">
                <div class="attributes container">
                    <?php foreach ($attributesColl as $attribute): ?>
                        <?php
                            $optionLabel = $block->getAttrLabel($attribute);
                            $attrOptions = $block->getAttrOptIdByLabel($attribute);
                        ?>

                        <?php if (count($attrOptions) > 1): ?>
                            <div class='attribute options-title <?php /* @noEscape */ echo $attribute ?>'><?php echo __("Select %1", $optionLabel) ?></div>
                        <?php endif; ?>

                        <div class='attribute-container'>
                            <ol class="items attribute-<?php /* @noEscape */ echo $attribute ?>">
                                <?php foreach ($attrOptions as $keys => $attrOption): ?>
                                    <?php if ($keys > 0): ?>
                                        <?php
                                            $value = $attrOption["value"];
                                            $label = $attrOption["label"]; 
                                            $inputId = "attr-" . $attribute . "-" . $value;
                                        ?>
                                        <li class="item">
                                            <input type='checkbox' value="<?= /* @noEscape */ $value ?>" class="option" name="ccsearch[<?= /* @noEscape */ $attribute ?>][]" id="<?= /* @noEscape */ $inputId ?>">
                                            <label for="<?= /* @noEscape */ $inputId ?>" class="label"><span><?= /* @noEscape */ $label ?></span></label>
                                        </li>
                                <?php endif; ?>
                                <?php endforeach; ?>
                            </ol>
                        </div>
                    <?php endforeach; ?>

                    <div class="search-price">
                        <label class="price label" for="price"><?php echo __('Price') ?></label>
                        <div class="input-range">
                            <input name="price_from" id="price" title="Price" class="input-price" type="number" pattern="\d*" maxlength="128">
                            <span class="separator">-</span>
                            <input name="price_to" id="price_to" title="Price" class="input-price" type="number" pattern="\d*" maxlength="128">
                            <small class="currency"><?php /* @noEscape */ echo __('(%1)', $block->getCurrentCurrencyCode()); ?></small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="actions-toolbar">
            <button type="submit" class="action search primary" title="<?= /* @noEscape */ __('Search') ?>" name="submit">
                <span><?php echo /* @noEscape */  __('Search') ?></span>
            </button>
        </div>
    </form>
    <div class="result" style="display:none"></div>
</div>

<script>
    require([
        'jquery', 
        'mage/url', 
        'Magento_Ui/js/modal/modal'
    ], function($, urlBuilder, modal) {
        $(document).ready(function() {
            var ccsearchForm   = $('.ccsearch-form');
            var ccsearchResult = $('.ccsearch-container .result');

            ccsearchForm.on('submit', function (e) {
                e.preventDefault();
                ccsearchForm   = $(this);
                ccsearchResult = ccsearchForm.parents('.ccsearch-container').find('> .result');

                ccsearchForm.hide();

                var url = urlBuilder.build('productfinder/search/result');
                $.ajax({
                    url: url,
                    type: "POST",
                    data: ccsearchForm.serialize(),
                    showLoader: true,
                    cache: false,
                    success: function(response) {
                        ccsearchResult.show();
                        ccsearchResult.html(response.output);
                    }
                });
            });

            // popup code
            var popupContainer = $('.ccsearch-container.popup-modal');

            if (typeof(popupContainer) != 'undefined' && popupContainer != false && popupContainer.length > 0) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: $.mage.__('Advance Product Search'),
                    buttons: [{
                        text: $.mage.__('Close'),
                        class: '',
                        click: function() {
                            this.closeModal();
                        }
                    }]
                };
                var popup = modal(options, popupContainer);

                $(".ccsearch.popup-modal").on('click', function(event) {
                    popupContainer.modal("openModal");
                    event.preventDefault();
                });
            }
        });
    });
</script>